[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py
testpaths = apps
addopts =
    -ra
    --strict-markers
    --cov=apps
    --cov=core
    --cov-config=.coveragerc
    --cov-report=term-missing
    --cov-report=html

markers =
    integration: hits a REAL Elasticsearch instance + seeded data
